# Taplo LSP schema specification
#:schema https://mise.en.dev/schema/mise.json

[tools]
apollo-rover = "latest"
bat = "latest"
btop = "latest"
caddy = "latest"
carapace = "latest"
claude = "latest"
cloc = "latest"
codex = "latest"
fd = "latest"
fzf = "latest"
gallery-dl = "latest"
ghcup = "latest"
github-cli = "latest"
glow = "latest"
golangci-lint = "latest"
gron = "latest"
jq = "latest"
jqp = "latest"
lazyssh = "latest"
lsd = "latest"
lua = "latest"
mongosh = "latest"
neovim = "latest"
node = "lts"
opencode = "latest"
pnpm = "latest"
rclone = "latest"
resvg = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
tmux = "latest"
tree-sitter = "latest"
usage = "latest"
watchexec = "latest"
yarn = "latest"
yazi = "latest"
yq = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
zoxide = "latest"

# Go bin that should be installed via local Go toolchain
"go:github.com/melkeydev/go-blueprint" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"
"go:golang.org/x/pkgsite/cmd/internal/pkgsite-cli" = "latest"

[env]
MISE_COLOR_THEME = "catppuccin"
OLLAMA_CONTEXT_LENGTH = "65536"
