# Taplo LSP schema specification
#:schema https://mise.en.dev/schema/mise.json

[settings]
dotfiles.root = "~/shared-configs/"
dotfiles.default_mode = "symlink"


[dotfiles]
"~/.agents" = { source = "~/shared-configs/.claude", mode = "symlink-each" }
"~/.claude" = { mode = "symlink-each" }
"~/.config" = { mode = "symlink-each" }
"~/.local" = { mode = "symlink-each" }
"~/.oh-my-zsh" = { mode = "symlink-each" }
"~/scripts/rc" = { mode = "symlink-each" }

"~/.gitattributes" = {}
"~/.gitconfig" = {}
"~/.prettierrc" = {}
"~/.sqliterc" = {}
"~/.vimrc" = {}
"~/.zshrc" = {}
"~/package.json" = {}


[tools]
bat = "latest"
btop = "latest"
caddy = "latest"
carapace = "latest"
claude = "latest"
fd = "latest"
fzf = "latest"
ghcup = "latest"
github-cli = "latest"
gron = "latest"
jq = "latest"
jqp = "latest"
lazyssh = "latest"
lsd = "latest"
lua = "latest"
mongosh = "latest"
neovim = "latest"
node = "lts"
opencode = "latest"
pnpm = "latest"
rclone = "latest"
resvg = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
tmux = "latest"
tree-sitter = "latest"
usage = "latest"
watchexec = "latest"
yarn = "latest"
yazi = "latest"
yq = "latest"
zoxide = "latest"

[env]
MISE_COLOR_THEME = "catppuccin"
OLLAMA_CONTEXT_LENGTH = "65536"
